services:
  transactional-db:
    image: postgres:18
    container_name: transactional-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactional_service
    ports:
      - "5434:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
